- .github/workflows/_deploy.yml
- .github/workflows/destroy-expired-workspaces.yml
- .github/workflows/merge.yml
- .github/workflows/pull-requests.yml
Upgraded github checkout version to 4
> [PI-106] dependabot_fix 

- feature_tests/end_to_end/environment.py
- feature_tests/end_to_end/steps/context.py
- feature_tests/end_to_end/steps/steps.py
- infrastructure/terraform/per_account/dev/parameters/main.tf
- infrastructure/terraform/per_account/int/parameters/main.tf
- infrastructure/terraform/per_account/prod/parameters/main.tf
- infrastructure/terraform/per_account/qa/parameters/main.tf
- infrastructure/terraform/per_account/ref/parameters/main.tf
- infrastructure/terraform/per_workspace/main.tf
- pyproject.toml
- scripts/infrastructure/policies/integration-test-policy.json
- src/api/authoriser/errors.py
- src/api/authoriser/index.py
- src/api/authoriser/tests/test_index.py
- src/layers/event/aws/client.py
Enabled apikey check on the authoriser
> [Feature PI-272] Enable Apikey 

- infrastructure/apigee/prod/.proxygen/credentials.yaml
- infrastructure/apigee/prod/.proxygen/settings.yaml
- infrastructure/terraform/per_workspace/locals.tf
- scripts/infrastructure/apigee/proxygen.sh
* Fixed INT deploy
* Made INT apigee app
> [Feature PI-282] Fix Integration deploy

- .github/CODEOWNERS
- .gitignore
- README.md
- scripts/builder/build.mk
> [Feature/PI-435] redline_repo_changes 

- .github/workflows/pull-requests.yml
- scripts/infrastructure/apigee.mk
- scripts/infrastructure/apigee/proxygen.sh
adjusted and added new proxygen delete
> [Feature/PI-379] fix_apigee_proxy_ref 

- infrastructure/terraform/per_workspace/main.tf
- infrastructure/terraform/per_workspace/modules/etl/sds/main.tf
- infrastructure/terraform/per_workspace/modules/etl/sds/trigger/main.tf
- infrastructure/terraform/per_workspace/modules/etl/sds/trigger/vars.tf
- infrastructure/terraform/per_workspace/modules/etl/sds/vars.tf
Added domain layer to update triggers
> [Feature PI-468] bulk_and_upload 

- scripts/test/test.mk
- src/etl/notify/tests/test_notify_lambda.py
Added internal flags to the S3 integration tests
> [Feature/PI-499] Fix_ci_s3_tests 

- src/layers/domain/core/cpm_system_id/tests/test_cpm_system_id_v1.py
- src/layers/domain/core/cpm_system_id/v1.py
> feature/PI-495-product_id_2 

- src/layers/etl_utils/worker/steps.py
> [feature/PI-465-extract_worker_test_bug] dont delete dataclass property

- src/api/tests/smoke_tests/test_sds_smoke.py
> [feature/PI-520-no_dev_sandbox_sds_smoke_test] no dev sandbox sds smoke test

- src/api/searchSdsEndpoint/src/v1/steps.py
- src/api/searchSdsEndpoint/tests/test_index.py
- src/layers/domain/api/sds/query.py
> [feature/PI-479-sds_endpoint_error_message] sds endpoint error message

- src/api/searchSdsDevice/src/v1/steps.py
- src/api/searchSdsEndpoint/src/v1/steps.py
- src/layers/domain/core/base.py
- src/layers/domain/core/device/v2.py
- src/layers/domain/repository/device_repository/tests/v2/test_device_repository_tags_v2.py
- src/layers/domain/repository/device_repository/v2.py
- src/layers/sds/cpm_translation/translations.py
> [feature/PI-515-query_by_tag_default] drop tags by default

- infrastructure/terraform/per_workspace/modules/etl/sds/main.tf
> [feature/PI-522-rename_lambda] rename lambdas

- .github/actions/components/caching/action.yml
- .github/workflows/_deploy.yml
- .gitignore
- scripts/builder/build.mk
- scripts/builder/timestamp_reset.sh
> [feature/PI-549-flaky_ci] always do checkout

- .sonarcloud.properties
> [feature/PI-548-sonarcloud_ignore_duplicated_index] sonarcloud ignore duplicated index

- .github/workflows/_deploy.yml
- .github/workflows/pull-requests.yml
- scripts/infrastructure/apigee.mk
- scripts/infrastructure/apigee/apigee.sh
- scripts/infrastructure/apigee/proxygen.sh
- src/api/tests/smoke_tests/config.py
- src/api/tests/smoke_tests/tests/test_smoke_test_utils.py
- src/api/tests/smoke_tests/utils.py
fixed up api name in the proxygen script
> [Feature PI-560-fix_proxygen_urls] 

- .github/workflows/pull-requests.yml
- scripts/infrastructure/terraform/terraform-commands.sh
- scripts/infrastructure/terraform/terraform-utils.sh
> [feature/PI-585-ci_in_dev] ci in dev

- src/api/createDeviceMessageHandlingSystem/tests/test_index.py
- src/api/createDeviceReferenceDataASActions/tests/test_index.py
- src/api/readDevice/src/v1/steps.py
- src/api/readDeviceReferenceData/src/v1/steps.py
- src/api/searchCpmProduct/src/v1/steps.py
- src/api/searchDeviceReferenceData/src/v1/steps.py
- src/api/tests/feature_tests/features/createCpmProduct.success.feature
- src/api/tests/feature_tests/features/createCpmProductForEpr.success.feature
- src/api/tests/feature_tests/features/createDevice.success.feature
- src/api/tests/feature_tests/features/createDeviceMessageHandlingSystem.success.feature
- src/api/tests/feature_tests/features/createDeviceReferenceData.success.feature
- src/api/tests/feature_tests/features/createDeviceReferenceDataAdditionalInteractions.success.feature
- src/api/tests/feature_tests/features/createDeviceReferenceDataMessageSet.success.feature
- src/api/tests/feature_tests/features/deleteCpmProduct.success.feature
- src/api/tests/feature_tests/features/readCpmProduct.success.feature
- src/api/tests/feature_tests/features/readDevice.success.feature
- src/api/tests/feature_tests/features/readDeviceReferenceData.success.feature
- src/api/tests/feature_tests/features/readProductTeam.success.feature
- src/api/tests/feature_tests/features/searchCpmProduct.success.feature
- src/layers/domain/api/common_steps/read_product.py
- src/layers/domain/core/device/v3.py
- src/layers/domain/repository/device_repository/tests/v3/test_device_repository_questionnaire_responses_v3.py
- src/layers/domain/repository/device_repository/v3.py
> [feature/PI-590-path_alias] path aliases

- src/api/searchCpmProduct/tests/test_index.py
- src/api/searchDeviceReferenceData/tests/test_index.py
- src/api/searchSdsDevice/tests/_test_index.py
- src/api/searchSdsEndpoint/tests/_test_index.py
- src/conftest.py
- src/etl/sds/tests/changelog/test_changelog_scenarios.py
- src/etl/sds/worker/update/tests/test_update_e2e.py
- src/layers/domain/api/common_steps/tests/test_create_product.py
- src/layers/domain/api/common_steps/tests/test_read_product.py
- src/layers/domain/repository/cpm_product_repository/tests/v1/test_cpm_product_repository_keys_v1.py
- src/layers/domain/repository/cpm_product_repository/tests/v1/test_cpm_product_repository_v1.py
- src/layers/domain/repository/cpm_product_repository/tests/v1/test_cpm_product_repository_v1_delete.py
- src/layers/domain/repository/device_reference_data_repository/tests/test_device_reference_data_repository_v1.py
- src/layers/domain/repository/device_repository/tests/utils.py
- src/layers/domain/repository/device_repository/tests/v1/test_device_repository_keys_v1.py
- src/layers/domain/repository/device_repository/tests/v1/test_device_repository_questionnaire_responses_v1.py
- src/layers/domain/repository/device_repository/tests/v1/test_device_repository_tags_v1.py
- src/layers/domain/repository/device_repository/tests/v1/test_device_repository_v1.py
- src/layers/domain/repository/product_team_repository/tests/test_product_team_repository_v1.py
- src/layers/domain/repository/repository/tests/model_v1.py
- src/layers/domain/repository/tests/test_cpm_system_id_repository.py
- src/layers/event/aws/client.py
- src/layers/sds/epr/bulk_create/tests/test_epr_product_team_repository.py
> [feature/PI-700-sleepy_tests] sleepier tests

- scripts/UI/ui.mk
- test_ui/product_id_flow/index.html
- test_ui/product_id_flow/src/App.tsx
- test_ui/product_id_flow/src/components/ProductReadFlow.tsx
Added in Mocked read with commented out real call
> feature/PI-843-read_product_ui 

- .github/workflows/pull-requests.yml
> feature/PI-858-fix_pr_boo_boo 
